-- ============================================================
-- seed_data.sql
-- Team LinkUp — Exercise_Library seed
--
-- 운동 동작 데이터는 이경님 운동 DB(fitteum_db.db) 를
-- tools/etl_fitteum.py 로 변환·삽입한다. (LK_0001 ~)
-- 따라서 이 파일에는 더 이상 임시 seed 동작을 두지 않는다.
--
-- 초기 동작 데이터 적재 순서:
--   1) init_db()                                  -- 빈 스키마 생성
--   2) python3 -m linkup.db.tools.etl_fitteum     -- 325개 적재
-- ============================================================
